In [1]:
print("Hello, World!")

Hello, World!

In [2]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    "mysql+pymysql",
    username="root",
    password="Password@123",
    host="localhost",
    port=3306,
    database="vendor_performance"
)

engine = create_engine(connection_url)

In [3]:
tables = pd.read_sql(
    "SHOW TABLES",
    engine
)

print(tables)

  Tables_in_vendor_performance
0              begin_inventory
1                end_inventory
2              purchase_prices
3                    purchases
4                        sales
5               vendor_invoice
6         vendor_sales_summary

In [4]:

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)

for table in tables.iloc[:, 0]:

    print('-' * 50, f'{table}', '-' * 50)

    count = pd.read_sql(
        f"SELECT COUNT(*) AS count FROM `{table}`",
        engine
    )['count'].values[0]

    print('Count of records:', count)
    print(pd.read_sql(
        f"SELECT * FROM `{table}` LIMIT 5", engine
    ))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records: 206529
         InventoryId  Store          City  Brand                  Description   Size  onHand  Price   startDate
0  1_HARDERSFIELD_58      1  HARDERSFIELD     58  Gekkeikan Black & Gold Sake  750mL       8  12.99  2024-01-01
1  1_HARDERSFIELD_60      1  HARDERSFIELD     60       Canadian Club 1858 VAP  750mL       7  10.99  2024-01-01
2  1_HARDERSFIELD_62      1  HARDERSFIELD     62     Herradura Silver Tequila  750mL       6  36.99  2024-01-01
3  1_HARDERSFIELD_63      1  HARDERSFIELD     63   Herradura Reposado Tequila  750mL       3  38.99  2024-01-01
4  1_HARDERSFIELD_72      1  HARDERSFIELD     72         No. 3 London Dry Gin  750mL       6  34.99  2024-01-01
-------------------------------------------------- end_inventory --------------------------------------------------
Count of records: 224489
         InventoryId  Store          City  Brand                  Description   Size  onHand  Price     endDate
0  1_HARDERSFIELD_58      1  HARDERSFIELD     58  Gekkeikan Black & Gold Sake  750mL      11  12.99  2024-12-31
1  1_HARDERSFIELD_62      1  HARDERSFIELD     62     Herradura Silver Tequila  750mL       7  36.99  2024-12-31
2  1_HARDERSFIELD_63      1  HARDERSFIELD     63   Herradura Reposado Tequila  750mL       7  38.99  2024-12-31
3  1_HARDERSFIELD_72      1  HARDERSFIELD     72         No. 3 London Dry Gin  750mL       4  34.99  2024-12-31
4  1_HARDERSFIELD_75      1  HARDERSFIELD     75    Three Olives Tomato Vodka  750mL       7  14.99  2024-12-31
-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records: 12261
   Brand                  Description  Price   Size Volume  Classification  PurchasePrice  VendorNumber                   VendorName
0     58  Gekkeikan Black & Gold Sake  12.99  750mL    750               1           9.28          8320  SHAW ROSS INT L IMP LTD
1     62     Herradura Silver Tequila  36.99  750mL    750               1          28.67          1128  BROWN-FORMAN CORP
2     63   Herradura Reposado Tequila  38.99  750mL    750               1          30.46          1128  BROWN-FORMAN CORP
3     72         No. 3 London Dry Gin  34.99  750mL    750               1          26.11          9165  ULTRA BEVERAGE COMPANY LLP
4     75    Three Olives Tomato Vodka  14.99  750mL    750               1          10.94          7245  PROXIMO SPIRITS INC.
-------------------------------------------------- purchases --------------------------------------------------
Count of records: 1643180
           InventoryId  Store  Brand                   Description   Size  VendorNumber                   VendorName  PONumber      PODate ReceivingDate InvoiceDate     PayDate  PurchasePrice  Quantity  Dollars  Classification
0    69_MOUNTMEND_8412     69   8412     Tequila Ocho Plata Fresno  750mL           105  ALTAMAR BRANDS LLC               8124  2023-12-21    2024-01-02  2024-01-04  2024-02-16          35.71         6   214.26               1
1     30_CULCHETH_5255     30   5255  TGI Fridays Ultimte Mudslide  1.75L          4466  AMERICAN VINTAGE BEVERAGE        8137  2023-12-22    2024-01-01  2024-01-07  2024-02-21           9.35         4    37.40               1
2    34_PITMERDEN_5215     34   5215  TGI Fridays Long Island Iced  1.75L          4466  AMERICAN VINTAGE BEVERAGE        8137  2023-12-22    2024-01-02  2024-01-07  2024-02-21           9.41         5    47.05               1
3  1_HARDERSFIELD_5255      1   5255  TGI Fridays Ultimte Mudslide  1.75L          4466  AMERICAN VINTAGE BEVERAGE        8137  2023-12-22    2024-01-01  2024-01-07  2024-02-21           9.35         6    56.10               1
4    76_DONCASTER_2034     76   2034     Glendalough Double Barrel  750mL           388  ATLANTIC IMPORTING COMPANY       8169  2023-12-24    2024-01-02  2024-01-09  2024-02-16          21.32         5   106.60               1
-------------------------------------------------- sales --------------------------------------------------
Count of records: 12825363
           InventoryId  Store  Brand                 Description        Size  SalesQuantity  SalesDollars  SalesPrice   SalesDate  Volume  Classification  ExciseTax  VendorNo                   VendorName
0  1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses       750mL              1         16.49       16.49  2024-01-01   750.0               1       0.79     12546  JIM BEAM BRANDS COMPANY
1  1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses       750mL              2         32.98       16.49  2024-01-02   750.0               1       1.57     12546  JIM BEAM BRANDS COMPANY
2  1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses       750mL              1         16.49       16.49  2024-01-03   750.0               1       0.79     12546  JIM BEAM BRANDS COMPANY
3  1_HARDERSFIELD_1004      1   1004  Jim Beam w/2 Rocks Glasses       750mL              1         14.49       14.49  2024-01-08   750.0               1       0.79     12546  JIM BEAM BRANDS COMPANY
4  1_HARDERSFIELD_1005      1   1005     Maker's Mark Combo Pack  375mL 2 Pk              2         69.98       34.99  2024-01-09   375.0               1       0.79     12546  JIM BEAM BRANDS COMPANY
-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records: 5543
   VendorNumber                   VendorName InvoiceDate  PONumber      PODate     PayDate  Quantity    Dollars  Freight Approval
0           105  ALTAMAR BRANDS LLC           2024-01-04      8124  2023-12-21  2024-02-16         6     214.26     3.47     None
1          4466  AMERICAN VINTAGE BEVERAGE    2024-01-07      8137  2023-12-22  2024-02-21        15     140.55     8.57     None
2           388  ATLANTIC IMPORTING COMPANY   2024-01-09      8169  2023-12-24  2024-02-16         5     106.60     4.61     None
3           480  BACARDI USA INC              2024-01-12      8106  2023-12-20  2024-02-05     10100  137483.78  2935.20     None
4           516  BANFI PRODUCTS CORP          2024-01-07      8170  2023-12-24  2024-02-12      1935   15527.25   429.20     None
-------------------------------------------------- vendor_sales_summary --------------------------------------------------
Count of records: 9896
   VendorNumber                VendorName  Brand              Description  PurchasePrice  ActualPrice  Volume  TotalPurchaseQuantity  TotalPurchaseDollars  TotalSalesQuantity  TotalSalesDollars  TotalSalesPrice  TotalExciseTax  FreightCost   GrossProfit  ProfitMargin  StockTurnover  SalestoPurchaseRatio
0          4425     MARTIGNETTI COMPANIES   3405    Tito's Handmade Vodka          23.19        28.99  1750.0               115609.0            2680972.71            160247.0       4.819073e+06        561512.37       294438.66    144929.24  2.138101e+06     44.367466       1.386112              1.797509
1          1128         BROWN-FORMAN CORP   1233  Jack Daniels No 7 Black          26.27        36.99  1750.0               101636.0            2669977.72            142049.0       5.101920e+06        672819.31       260999.20     68601.68  2.431942e+06     47.667192       1.397625              1.910847
2         17035         PERNOD RICARD USA   8068         Absolut 80 Proof          18.24        24.99  1750.0               136129.0            2482992.96            187140.0       4.538121e+06        461140.15       343854.07    123780.22  2.055128e+06     45.285875       1.374725              1.827682
3          3960  DIAGEO NORTH AMERICA INC   3545          Ketel One Vodka          21.89        29.99  1750.0                95215.0            2084256.35            135838.0       4.223108e+06        545778.28       249587.83    257032.07  2.138851e+06     50.646383       1.426645              2.026194
4          3960  DIAGEO NORTH AMERICA INC   4261   Capt Morgan Spiced Rum          16.17        22.99  1750.0               119516.0            1932573.72            200412.0       4.475973e+06        420050.01       368242.80    257032.07  2.543399e+06     56.823382       1.676863              2.316068

In [5]:
purchases = pd.read_sql_query("select * from purchases where VendorNumber = 4466", engine)

In [6]:
purchases

              InventoryId  Store  Brand                   Description   Size  VendorNumber                   VendorName  PONumber      PODate ReceivingDate InvoiceDate     PayDate  PurchasePrice  Quantity  Dollars  Classification
0        30_CULCHETH_5255     30   5255  TGI Fridays Ultimte Mudslide  1.75L          4466  AMERICAN VINTAGE BEVERAGE        8137  2023-12-22    2024-01-01  2024-01-07  2024-02-21           9.35         4    37.40               1
1       34_PITMERDEN_5215     34   5215  TGI Fridays Long Island Iced  1.75L          4466  AMERICAN VINTAGE BEVERAGE        8137  2023-12-22    2024-01-02  2024-01-07  2024-02-21           9.41         5    47.05               1
2     1_HARDERSFIELD_5255      1   5255  TGI Fridays Ultimte Mudslide  1.75L          4466  AMERICAN VINTAGE BEVERAGE        8137  2023-12-22    2024-01-01  2024-01-07  2024-02-21           9.35         6    56.10               1
3       38_GOULCREST_5215     38   5215  TGI Fridays Long Island Iced  1.75L          4466  AMERICAN VINTAGE BEVERAGE        8207  2023-12-27    2024-01-07  2024-01-19  2024-02-26           9.41         6    56.46               1
4     59_CLAETHORPES_5215     59   5215  TGI Fridays Long Island Iced  1.75L          4466  AMERICAN VINTAGE BEVERAGE        8207  2023-12-27    2024-01-05  2024-01-19  2024-02-26           9.41         6    56.46               1
...                   ...    ...    ...                           ...    ...           ...                          ...       ...         ...           ...         ...         ...            ...       ...      ...             ...
1571   13_TARMSWORTH_5255     13   5255  TGI Fridays Ultimte Mudslide  1.75L          4466  AMERICAN VINTAGE BEVERAGE       11993  2024-09-07    2024-09-14  2024-09-25  2024-10-23           9.35         6    56.10               1
1572     30_CULCHETH_5215     30   5215  TGI Fridays Long Island Iced  1.75L          4466  AMERICAN VINTAGE BEVERAGE       11993  2024-09-07    2024-09-15  2024-09-25  2024-10-23           9.41         6    56.46               1
1573      54_GUTHRAM_5255     54   5255  TGI Fridays Ultimte Mudslide  1.75L          4466  AMERICAN VINTAGE BEVERAGE       11993  2024-09-07    2024-09-13  2024-09-25  2024-10-23           9.35         5    46.75               1
1574      54_GUTHRAM_5215     54   5215  TGI Fridays Long Island Iced  1.75L          4466  AMERICAN VINTAGE BEVERAGE       11993  2024-09-07    2024-09-16  2024-09-25  2024-10-23           9.41         5    47.05               1
1575  59_CLAETHORPES_5215     59   5215  TGI Fridays Long Island Iced  1.75L          4466  AMERICAN VINTAGE BEVERAGE       11993  2024-09-07    2024-09-14  2024-09-25  2024-10-23           9.41         6    56.46               1

[1576 rows x 16 columns]

In [7]:
purchase_prices = pd.read_sql_query("select * from purchase_prices where VendorNumber = 4466", engine)
purchase_prices

   Brand                   Description  Price    Size Volume  Classification  PurchasePrice  VendorNumber                   VendorName
0   5215  TGI Fridays Long Island Iced  12.99  1750mL   1750               1           9.41          4466  AMERICAN VINTAGE BEVERAGE
1   5255  TGI Fridays Ultimte Mudslide  12.99  1750mL   1750               1           9.35          4466  AMERICAN VINTAGE BEVERAGE
2   3140      TGI Fridays Orange Dream  14.99  1750mL   1750               1          11.19          4466  AMERICAN VINTAGE BEVERAGE

In [8]:
vendor_invoice = pd.read_sql_query("select * from vendor_invoice where VendorNumber = 4466", engine)
vendor_invoice

    VendorNumber                   VendorName InvoiceDate  PONumber      PODate     PayDate  Quantity   Dollars  Freight Approval
0           4466  AMERICAN VINTAGE BEVERAGE    2024-01-07      8137  2023-12-22  2024-02-21        15    140.55     8.57     None
1           4466  AMERICAN VINTAGE BEVERAGE    2024-01-19      8207  2023-12-27  2024-02-26       335   3142.33    16.97     None
2           4466  AMERICAN VINTAGE BEVERAGE    2024-01-18      8307  2024-01-03  2024-02-18        41    383.35     1.99     None
3           4466  AMERICAN VINTAGE BEVERAGE    2024-01-27      8469  2024-01-14  2024-03-11        72    673.20     3.30     None
4           4466  AMERICAN VINTAGE BEVERAGE    2024-02-04      8532  2024-01-19  2024-03-15        79    740.21     3.48     None
5           4466  AMERICAN VINTAGE BEVERAGE    2024-02-09      8604  2024-01-24  2024-03-15       347   3261.37    17.61     None
6           4466  AMERICAN VINTAGE BEVERAGE    2024-02-17      8793  2024-02-05  2024-04-02        72    675.36     3.17     None
7           4466  AMERICAN VINTAGE BEVERAGE    2024-03-01      8892  2024-02-12  2024-03-28       117   1096.05     5.15     None
8           4466  AMERICAN VINTAGE BEVERAGE    2024-03-07      8995  2024-02-19  2024-04-02       129   1209.27     5.44     None
9           4466  AMERICAN VINTAGE BEVERAGE    2024-03-12      9033  2024-02-22  2024-04-16       147   1377.87     6.61     None
10          4466  AMERICAN VINTAGE BEVERAGE    2024-03-16      9180  2024-03-03  2024-04-19       211   1979.33     9.50     None
11          4466  AMERICAN VINTAGE BEVERAGE    2024-03-23      9244  2024-03-08  2024-04-21       161   1510.69     6.95     None
12          4466  AMERICAN VINTAGE BEVERAGE    2024-03-31      9371  2024-03-17  2024-05-13       176   1649.20     8.91     None
13          4466  AMERICAN VINTAGE BEVERAGE    2024-04-09      9491  2024-03-24  2024-05-08       215   2016.43    10.08     None
14          4466  AMERICAN VINTAGE BEVERAGE    2024-04-17      9583  2024-03-31  2024-05-12       110   1035.10     5.69     None
15          4466  AMERICAN VINTAGE BEVERAGE    2024-04-20      9639  2024-04-04  2024-06-04       515   5323.01    25.02     None
16          4466  AMERICAN VINTAGE BEVERAGE    2024-04-29      9800  2024-04-15  2024-06-07       275   2775.01    13.60     None
17          4466  AMERICAN VINTAGE BEVERAGE    2024-05-09      9886  2024-04-21  2024-06-12       312   3050.86    13.73     None
18          4466  AMERICAN VINTAGE BEVERAGE    2024-05-14      9999  2024-04-29  2024-06-26       310   3117.82    14.97     None
19          4466  AMERICAN VINTAGE BEVERAGE    2024-05-16     10095  2024-05-06  2024-06-27       215   2123.01    11.46     None
20          4466  AMERICAN VINTAGE BEVERAGE    2024-05-28     10169  2024-05-11  2024-07-04       327   3298.55    15.83     None
21          4466  AMERICAN VINTAGE BEVERAGE    2024-06-04     10257  2024-05-17  2024-07-08       376   3708.18    20.39     None
22          4466  AMERICAN VINTAGE BEVERAGE    2024-06-12     10346  2024-05-23  2024-07-20       640   6458.38    29.71     None
23          4466  AMERICAN VINTAGE BEVERAGE    2024-06-17     10445  2024-05-30  2024-07-19       288   2937.56    15.86     None
24          4466  AMERICAN VINTAGE BEVERAGE    2024-06-22     10600  2024-06-09  2024-08-01       308   3213.28    17.03     None
25          4466  AMERICAN VINTAGE BEVERAGE    2024-06-29     10695  2024-06-16  2024-08-12       143   1585.75     8.09     None
26          4466  AMERICAN VINTAGE BEVERAGE    2024-07-09     10777  2024-06-22  2024-08-15        18    179.88     0.99     None
27          4466  AMERICAN VINTAGE BEVERAGE    2024-07-08     10836  2024-06-25  2024-08-14         8     85.96     0.43     None
28          4466  AMERICAN VINTAGE BEVERAGE    2024-07-11     10969  2024-06-29  2024-08-18        94    993.12     5.06     None
29          4466  AMERICAN VINTAGE BEVERAGE    2024-07-19     11085  2024-07-06  2024-09-04       601   5883.09    31.18     None
30          4466  AMERICAN VINTAGE BEVERAGE    2024-07-26     11187  2024-07-14  2024-08-26      1535  15406.69    77.03     None
31          4466  AMERICAN VINTAGE BEVERAGE    2024-08-03     11244  2024-07-18  2024-09-04       266   2888.22    15.31     None
32          4466  AMERICAN VINTAGE BEVERAGE    2024-08-11     11362  2024-07-26  2024-09-24       206   2171.64    11.08     None
33          4466  AMERICAN VINTAGE BEVERAGE    2024-08-18     11489  2024-08-04  2024-09-16       768   7292.98    37.92     None
34          4466  AMERICAN VINTAGE BEVERAGE    2024-08-24     11540  2024-08-08  2024-10-02      1207  12242.43    64.88     None
35          4466  AMERICAN VINTAGE BEVERAGE    2024-09-02     11716  2024-08-19  2024-09-29       433   4334.43    20.37     None
36          4466  AMERICAN VINTAGE BEVERAGE    2024-09-12     11771  2024-08-23  2024-10-11       370   3640.18    18.20     None
37          4466  AMERICAN VINTAGE BEVERAGE    2024-09-20     11901  2024-09-01  2024-10-30       358   3626.74    16.32     None
38          4466  AMERICAN VINTAGE BEVERAGE    2024-09-25     11993  2024-09-07  2024-10-23       233   2264.85    12.23     None
39          4466  AMERICAN VINTAGE BEVERAGE    2024-10-01     12125  2024-09-16  2024-11-07       284   2813.46    15.47     None
40          4466  AMERICAN VINTAGE BEVERAGE    2024-10-08     12235  2024-09-23  2024-11-20       258   2592.08    11.92     None
41          4466  AMERICAN VINTAGE BEVERAGE    2024-10-09     12253  2024-09-23  2024-11-14         1     11.19     0.05     None
42          4466  AMERICAN VINTAGE BEVERAGE    2024-10-12     12321  2024-09-26  2024-11-19       172   1685.98     7.59     None
43          4466  AMERICAN VINTAGE BEVERAGE    2024-10-20     12466  2024-10-05  2024-11-26       280   2798.60    14.55     None
44          4466  AMERICAN VINTAGE BEVERAGE    2024-10-27     12515  2024-10-09  2024-11-30       178   1763.28     8.64     None
45          4466  AMERICAN VINTAGE BEVERAGE    2024-11-07     12702  2024-10-21  2024-12-11       183   1812.77     8.70     None
46          4466  AMERICAN VINTAGE BEVERAGE    2024-11-12     12752  2024-10-25  2024-12-11       216   2156.16    10.57     None
47          4466  AMERICAN VINTAGE BEVERAGE    2024-11-20     12828  2024-10-30  2024-12-18       262   2597.36    12.99     None
48          4466  AMERICAN VINTAGE BEVERAGE    2024-11-27     12929  2024-11-06  2025-01-04       270   2622.32    12.85     None
49          4466  AMERICAN VINTAGE BEVERAGE    2024-11-28     13092  2024-11-16  2024-12-30       209   2036.17    11.20     None
50          4466  AMERICAN VINTAGE BEVERAGE    2024-12-06     13134  2024-11-20  2025-01-18       305   3018.89    15.70     None
51          4466  AMERICAN VINTAGE BEVERAGE    2024-12-16     13254  2024-11-28  2025-01-13       262   2530.36    11.39     None
52          4466  AMERICAN VINTAGE BEVERAGE    2024-12-26     13432  2024-12-09  2025-01-27       231   2263.43    11.32     None
53          4466  AMERICAN VINTAGE BEVERAGE    2024-12-30     13483  2024-12-13  2025-02-11       221   2178.27    11.33     None
54          4466  AMERICAN VINTAGE BEVERAGE    2025-01-09     13627  2024-12-22  2025-02-05       413   3985.03    19.53     None

In [9]:
sales = pd.read_sql_query("select * from sales where VendorNo = 4466", engine)
sales

              InventoryId  Store  Brand                   Description   Size  SalesQuantity  SalesDollars  SalesPrice   SalesDate  Volume  Classification  ExciseTax  VendorNo                   VendorName
0     1_HARDERSFIELD_5215      1   5215  TGI Fridays Long Island Iced  1.75L              1         12.99       12.99  2024-01-09  1750.0               1       1.84      4466  AMERICAN VINTAGE BEVERAGE
1     1_HARDERSFIELD_5215      1   5215  TGI Fridays Long Island Iced  1.75L              1         12.99       12.99  2024-01-12  1750.0               1       1.84      4466  AMERICAN VINTAGE BEVERAGE
2     1_HARDERSFIELD_5215      1   5215  TGI Fridays Long Island Iced  1.75L              1         12.99       12.99  2024-01-15  1750.0               1       1.84      4466  AMERICAN VINTAGE BEVERAGE
3     1_HARDERSFIELD_5215      1   5215  TGI Fridays Long Island Iced  1.75L              1         12.99       12.99  2024-01-21  1750.0               1       1.84      4466  AMERICAN VINTAGE BEVERAGE
4     1_HARDERSFIELD_5215      1   5215  TGI Fridays Long Island Iced  1.75L              1         12.99       12.99  2024-01-23  1750.0               1       1.84      4466  AMERICAN VINTAGE BEVERAGE
...                   ...    ...    ...                           ...    ...            ...           ...         ...         ...     ...             ...        ...       ...                          ...
9448     9_BLACKPOOL_5215      9   5215  TGI Fridays Long Island Iced  1.75L              1         12.99       12.99  2024-12-21  1750.0               1       1.84      4466  AMERICAN VINTAGE BEVERAGE
9449     9_BLACKPOOL_5255      9   5255  TGI Fridays Ultimte Mudslide  1.75L              1         12.99       12.99  2024-12-02  1750.0               1       1.84      4466  AMERICAN VINTAGE BEVERAGE
9450     9_BLACKPOOL_5255      9   5255  TGI Fridays Ultimte Mudslide  1.75L              1         12.99       12.99  2024-12-09  1750.0               1       1.84      4466  AMERICAN VINTAGE BEVERAGE
9451     9_BLACKPOOL_5255      9   5255  TGI Fridays Ultimte Mudslide  1.75L              1         12.99       12.99  2024-12-23  1750.0               1       1.84      4466  AMERICAN VINTAGE BEVERAGE
9452     9_BLACKPOOL_5255      9   5255  TGI Fridays Ultimte Mudslide  1.75L              1         12.99       12.99  2024-12-31  1750.0               1       1.84      4466  AMERICAN VINTAGE BEVERAGE

[9453 rows x 14 columns]

In [10]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              3673  41100.87
5215  9.41               3751  35296.91
5255  9.35               4609  43094.15

In [11]:
vendor_invoice

    VendorNumber                   VendorName InvoiceDate  PONumber      PODate     PayDate  Quantity   Dollars  Freight Approval
0           4466  AMERICAN VINTAGE BEVERAGE    2024-01-07      8137  2023-12-22  2024-02-21        15    140.55     8.57     None
1           4466  AMERICAN VINTAGE BEVERAGE    2024-01-19      8207  2023-12-27  2024-02-26       335   3142.33    16.97     None
2           4466  AMERICAN VINTAGE BEVERAGE    2024-01-18      8307  2024-01-03  2024-02-18        41    383.35     1.99     None
3           4466  AMERICAN VINTAGE BEVERAGE    2024-01-27      8469  2024-01-14  2024-03-11        72    673.20     3.30     None
4           4466  AMERICAN VINTAGE BEVERAGE    2024-02-04      8532  2024-01-19  2024-03-15        79    740.21     3.48     None
5           4466  AMERICAN VINTAGE BEVERAGE    2024-02-09      8604  2024-01-24  2024-03-15       347   3261.37    17.61     None
6           4466  AMERICAN VINTAGE BEVERAGE    2024-02-17      8793  2024-02-05  2024-04-02        72    675.36     3.17     None
7           4466  AMERICAN VINTAGE BEVERAGE    2024-03-01      8892  2024-02-12  2024-03-28       117   1096.05     5.15     None
8           4466  AMERICAN VINTAGE BEVERAGE    2024-03-07      8995  2024-02-19  2024-04-02       129   1209.27     5.44     None
9           4466  AMERICAN VINTAGE BEVERAGE    2024-03-12      9033  2024-02-22  2024-04-16       147   1377.87     6.61     None
10          4466  AMERICAN VINTAGE BEVERAGE    2024-03-16      9180  2024-03-03  2024-04-19       211   1979.33     9.50     None
11          4466  AMERICAN VINTAGE BEVERAGE    2024-03-23      9244  2024-03-08  2024-04-21       161   1510.69     6.95     None
12          4466  AMERICAN VINTAGE BEVERAGE    2024-03-31      9371  2024-03-17  2024-05-13       176   1649.20     8.91     None
13          4466  AMERICAN VINTAGE BEVERAGE    2024-04-09      9491  2024-03-24  2024-05-08       215   2016.43    10.08     None
14          4466  AMERICAN VINTAGE BEVERAGE    2024-04-17      9583  2024-03-31  2024-05-12       110   1035.10     5.69     None
15          4466  AMERICAN VINTAGE BEVERAGE    2024-04-20      9639  2024-04-04  2024-06-04       515   5323.01    25.02     None
16          4466  AMERICAN VINTAGE BEVERAGE    2024-04-29      9800  2024-04-15  2024-06-07       275   2775.01    13.60     None
17          4466  AMERICAN VINTAGE BEVERAGE    2024-05-09      9886  2024-04-21  2024-06-12       312   3050.86    13.73     None
18          4466  AMERICAN VINTAGE BEVERAGE    2024-05-14      9999  2024-04-29  2024-06-26       310   3117.82    14.97     None
19          4466  AMERICAN VINTAGE BEVERAGE    2024-05-16     10095  2024-05-06  2024-06-27       215   2123.01    11.46     None
20          4466  AMERICAN VINTAGE BEVERAGE    2024-05-28     10169  2024-05-11  2024-07-04       327   3298.55    15.83     None
21          4466  AMERICAN VINTAGE BEVERAGE    2024-06-04     10257  2024-05-17  2024-07-08       376   3708.18    20.39     None
22          4466  AMERICAN VINTAGE BEVERAGE    2024-06-12     10346  2024-05-23  2024-07-20       640   6458.38    29.71     None
23          4466  AMERICAN VINTAGE BEVERAGE    2024-06-17     10445  2024-05-30  2024-07-19       288   2937.56    15.86     None
24          4466  AMERICAN VINTAGE BEVERAGE    2024-06-22     10600  2024-06-09  2024-08-01       308   3213.28    17.03     None
25          4466  AMERICAN VINTAGE BEVERAGE    2024-06-29     10695  2024-06-16  2024-08-12       143   1585.75     8.09     None
26          4466  AMERICAN VINTAGE BEVERAGE    2024-07-09     10777  2024-06-22  2024-08-15        18    179.88     0.99     None
27          4466  AMERICAN VINTAGE BEVERAGE    2024-07-08     10836  2024-06-25  2024-08-14         8     85.96     0.43     None
28          4466  AMERICAN VINTAGE BEVERAGE    2024-07-11     10969  2024-06-29  2024-08-18        94    993.12     5.06     None
29          4466  AMERICAN VINTAGE BEVERAGE    2024-07-19     11085  2024-07-06  2024-09-04       601   5883.09    31.18     None
30          4466  AMERICAN VINTAGE BEVERAGE    2024-07-26     11187  2024-07-14  2024-08-26      1535  15406.69    77.03     None
31          4466  AMERICAN VINTAGE BEVERAGE    2024-08-03     11244  2024-07-18  2024-09-04       266   2888.22    15.31     None
32          4466  AMERICAN VINTAGE BEVERAGE    2024-08-11     11362  2024-07-26  2024-09-24       206   2171.64    11.08     None
33          4466  AMERICAN VINTAGE BEVERAGE    2024-08-18     11489  2024-08-04  2024-09-16       768   7292.98    37.92     None
34          4466  AMERICAN VINTAGE BEVERAGE    2024-08-24     11540  2024-08-08  2024-10-02      1207  12242.43    64.88     None
35          4466  AMERICAN VINTAGE BEVERAGE    2024-09-02     11716  2024-08-19  2024-09-29       433   4334.43    20.37     None
36          4466  AMERICAN VINTAGE BEVERAGE    2024-09-12     11771  2024-08-23  2024-10-11       370   3640.18    18.20     None
37          4466  AMERICAN VINTAGE BEVERAGE    2024-09-20     11901  2024-09-01  2024-10-30       358   3626.74    16.32     None
38          4466  AMERICAN VINTAGE BEVERAGE    2024-09-25     11993  2024-09-07  2024-10-23       233   2264.85    12.23     None
39          4466  AMERICAN VINTAGE BEVERAGE    2024-10-01     12125  2024-09-16  2024-11-07       284   2813.46    15.47     None
40          4466  AMERICAN VINTAGE BEVERAGE    2024-10-08     12235  2024-09-23  2024-11-20       258   2592.08    11.92     None
41          4466  AMERICAN VINTAGE BEVERAGE    2024-10-09     12253  2024-09-23  2024-11-14         1     11.19     0.05     None
42          4466  AMERICAN VINTAGE BEVERAGE    2024-10-12     12321  2024-09-26  2024-11-19       172   1685.98     7.59     None
43          4466  AMERICAN VINTAGE BEVERAGE    2024-10-20     12466  2024-10-05  2024-11-26       280   2798.60    14.55     None
44          4466  AMERICAN VINTAGE BEVERAGE    2024-10-27     12515  2024-10-09  2024-11-30       178   1763.28     8.64     None
45          4466  AMERICAN VINTAGE BEVERAGE    2024-11-07     12702  2024-10-21  2024-12-11       183   1812.77     8.70     None
46          4466  AMERICAN VINTAGE BEVERAGE    2024-11-12     12752  2024-10-25  2024-12-11       216   2156.16    10.57     None
47          4466  AMERICAN VINTAGE BEVERAGE    2024-11-20     12828  2024-10-30  2024-12-18       262   2597.36    12.99     None
48          4466  AMERICAN VINTAGE BEVERAGE    2024-11-27     12929  2024-11-06  2025-01-04       270   2622.32    12.85     None
49          4466  AMERICAN VINTAGE BEVERAGE    2024-11-28     13092  2024-11-16  2024-12-30       209   2036.17    11.20     None
50          4466  AMERICAN VINTAGE BEVERAGE    2024-12-06     13134  2024-11-20  2025-01-18       305   3018.89    15.70     None
51          4466  AMERICAN VINTAGE BEVERAGE    2024-12-16     13254  2024-11-28  2025-01-13       262   2530.36    11.39     None
52          4466  AMERICAN VINTAGE BEVERAGE    2024-12-26     13432  2024-12-09  2025-01-27       231   2263.43    11.32     None
53          4466  AMERICAN VINTAGE BEVERAGE    2024-12-30     13483  2024-12-13  2025-02-11       221   2178.27    11.33     None
54          4466  AMERICAN VINTAGE BEVERAGE    2025-01-09     13627  2024-12-22  2025-02-05       413   3985.03    19.53     None

In [12]:
vendor_invoice['PONumber'].nunique()

55

In [13]:
vendor_invoice.shape

(55, 10)

In [14]:
sales.groupby(['Brand'])[['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
3140       50531.10    30071.85           3890
5215       60416.49    41542.02           4651
5255       79187.04    51180.60           6096

In [15]:
freight_summary = pd.read_sql("select "
"VendorNumber,"
"SUM(Freight) as TotalFreightCost"
" from vendor_invoice " 
"Group by VendorNumber " 
"order by VendorNumber", engine)
freight_summary

     VendorNumber  TotalFreightCost
0               2             27.08
1              54              0.48
2              60            367.52
3             105             62.39
4             200              6.19
..            ...               ...
121         98450            856.02
122         99166            130.09
123        172662            178.34
124        173357            202.50
125        201359              0.09

[126 rows x 2 columns]

In [16]:
purchase_prices

   Brand                   Description  Price    Size Volume  Classification  PurchasePrice  VendorNumber                   VendorName
0   5215  TGI Fridays Long Island Iced  12.99  1750mL   1750               1           9.41          4466  AMERICAN VINTAGE BEVERAGE
1   5255  TGI Fridays Ultimte Mudslide  12.99  1750mL   1750               1           9.35          4466  AMERICAN VINTAGE BEVERAGE
2   3140      TGI Fridays Orange Dream  14.99  1750mL   1750               1          11.19          4466  AMERICAN VINTAGE BEVERAGE

In [19]:
purchases.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber', 'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate', 'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'], dtype='str')

In [20]:
purchase_prices.columns

Index(['Brand', 'Description', 'Price', 'Size', 'Volume', 'Classification', 'PurchasePrice', 'VendorNumber', 'VendorName'], dtype='str')

In [21]:
result = pd.read_sql_query("""
SELECT
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price AS ActualPrice,
    SUM(p.Quantity) AS TotalPurchaseQuantity,
    SUM(p.Dollars) AS TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp
    ON p.Brand = pp.Brand
    Where p.purchasePrice > 0
GROUP BY
    p.VendorNumber,
    p.VendorName,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price
ORDER BY TotalPurchaseDollars
""", engine)

print(result)

      VendorNumber                   VendorName  Brand  PurchasePrice Volume  ActualPrice  TotalPurchaseQuantity  TotalPurchaseDollars
0             7245  PROXIMO SPIRITS INC.          3065           0.71     50         0.99                    1.0                  0.71
1             3960  DIAGEO NORTH AMERICA INC      3775           0.73     50         0.99                    1.0                  0.73
2             8004  SAZERAC CO INC                5683           0.39     50         0.49                    6.0                  2.34
3             9815  WINE GROUP INC                8527           1.32    750         4.99                    2.0                  2.64
4             3960  DIAGEO NORTH AMERICA INC      2626           1.42     50         1.99                    2.0                  2.84
...            ...                          ...    ...            ...    ...          ...                    ...                   ...
9891          3960  DIAGEO NORTH AMERICA INC      4261          16.17   1750        22.99               119516.0            1932573.72
9892          3960  DIAGEO NORTH AMERICA INC      3545          21.89   1750        29.99                95215.0            2084256.35
9893         17035  PERNOD RICARD USA             8068          18.24   1750        24.99               136129.0            2482992.96
9894          1128  BROWN-FORMAN CORP             1233          26.27   1750        36.99               101636.0            2669977.72
9895          4425        MARTIGNETTI COMPANIES   3405          23.19   1750        28.99               115609.0            2680972.71

[9896 rows x 8 columns]

In [22]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity', 'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification', 'ExciseTax', 'VendorNo', 'VendorName'], dtype='str')

In [23]:
pd.read_sql("""SELECT
VendorNo,
Brand,
SUM(SalesDollars) AS TotalSalesDollars,
SUM(SalesPrice) AS TotalSalesPrice,
SUM(SalesQuantity) AS TotalSalesQuantity,
SUM(ExciseTax) as TotalExciseTax
FROM sales
GROUP BY VendorNo, Brand
ORDER BY TotalSalesDollars""",engine)

       VendorNo  Brand  TotalSalesDollars  TotalSalesPrice  TotalSalesQuantity  TotalExciseTax
0          8004   5287       9.800000e-01             0.98                 2.0            0.10
1          9206   2773       9.900000e-01             0.99                 1.0            0.05
2          3924   9123       1.980000e+00             0.99                 2.0            0.10
3          3252   3933       1.980000e+00             0.99                 2.0            0.10
4         10050   3623       1.980000e+00             1.98                 2.0            0.10
...         ...    ...                ...              ...                 ...             ...
11267      3960   3545       4.223108e+06        545778.28            135838.0       249587.83
11268      3960   4261       4.475973e+06        420050.01            200412.0       368242.80
11269     17035   8068       4.538121e+06        461140.15            187140.0       343854.07
11270      4425   3405       4.819073e+06        561512.37            160247.0       294438.66
11271      1128   1233       5.101920e+06        672819.31            142049.0       260999.20

[11272 rows x 6 columns]

In [24]:
vendor_sales_summary = pd.read_sql("""
WITH FreightSummary AS (
    SELECT
        VendorNumber,
        SUM(Freight) AS FreightCost
    FROM vendor_invoice
    GROUP BY VendorNumber
),

PurchaseSummary AS (
    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price AS ActualPrice,
        pp.Volume,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) AS TotalPurchaseDollars
    FROM purchases p
    JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price,
        pp.Volume
),

SalesSummary AS (
    SELECT
        VendorNo,
        Brand,
        SUM(SalesQuantity) AS TotalSalesQuantity,
        SUM(SalesDollars) AS TotalSalesDollars,
        SUM(SalesPrice) AS TotalSalesPrice,
        SUM(ExciseTax) AS TotalExciseTax
    FROM sales
    GROUP BY
        VendorNo,
        Brand
)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    fs.FreightCost

FROM PurchaseSummary ps

LEFT JOIN SalesSummary ss
    ON ps.VendorNumber = ss.VendorNo
    AND ps.Brand = ss.Brand

LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber

ORDER BY ps.TotalPurchaseDollars DESC
""", engine)

In [25]:
vendor_sales_summary

      VendorNumber                   VendorName  Brand                   Description  PurchasePrice  ActualPrice Volume  TotalPurchaseQuantity  TotalPurchaseDollars  TotalSalesQuantity  TotalSalesDollars  TotalSalesPrice  TotalExciseTax  FreightCost
0             4425        MARTIGNETTI COMPANIES   3405         Tito's Handmade Vodka          23.19        28.99   1750               115609.0            2680972.71            160247.0       4.819073e+06        561512.37       294438.66    144929.24
1             1128  BROWN-FORMAN CORP             1233       Jack Daniels No 7 Black          26.27        36.99   1750               101636.0            2669977.72            142049.0       5.101920e+06        672819.31       260999.20     68601.68
2            17035  PERNOD RICARD USA             8068              Absolut 80 Proof          18.24        24.99   1750               136129.0            2482992.96            187140.0       4.538121e+06        461140.15       343854.07    123780.22
3             3960  DIAGEO NORTH AMERICA INC      3545               Ketel One Vodka          21.89        29.99   1750                95215.0            2084256.35            135838.0       4.223108e+06        545778.28       249587.83    257032.07
4             3960  DIAGEO NORTH AMERICA INC      4261        Capt Morgan Spiced Rum          16.17        22.99   1750               119516.0            1932573.72            200412.0       4.475973e+06        420050.01       368242.80    257032.07
...            ...                          ...    ...                           ...            ...          ...    ...                    ...                   ...                 ...                ...              ...             ...          ...
9891          3960  DIAGEO NORTH AMERICA INC      2626             Crown Royal Apple           1.42         1.99     50                    2.0                  2.84                14.0       2.786000e+01             5.97            0.73    257032.07
9892          9815  WINE GROUP INC                8527   Concannon Glen Ellen Wh Zin           1.32         4.99    750                    2.0                  2.64                 5.0       1.595000e+01            10.96            0.55     27100.41
9893          8004  SAZERAC CO INC                5683   Dr McGillicuddy's Apple Pie           0.39         0.49     50                    6.0                  2.34               134.0       6.566000e+01             1.47            7.04     50293.62
9894          3960  DIAGEO NORTH AMERICA INC      3775  Smirnoff Sorbet Pine/Coconut           0.73         0.99     50                    1.0                  0.73               120.0       1.188000e+02            46.53            6.20    257032.07
9895          7245  PROXIMO SPIRITS INC.          3065      Three Olives Grape Vodka           0.71         0.99     50                    1.0                  0.71                86.0       8.514000e+01            33.66            4.46     38994.78

[9896 rows x 14 columns]

In [26]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                   str
Brand                      int64
Description                  str
PurchasePrice            float64
ActualPrice              float64
Volume                       str
TotalPurchaseQuantity    float64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [27]:
vendor_sales_summary.isnull().sum()

VendorNumber              0
VendorName                0
Brand                     0
Description               0
PurchasePrice             0
ActualPrice               0
Volume                    0
TotalPurchaseQuantity     0
TotalPurchaseDollars      0
TotalSalesQuantity       54
TotalSalesDollars        54
TotalSalesPrice          54
TotalExciseTax           54
FreightCost               0
dtype: int64

In [28]:
vendor_sales_summary['VendorName'].unique()

<StringArray>
[      'MARTIGNETTI COMPANIES', 'BROWN-FORMAN CORP          ', 'PERNOD RICARD USA          ', 'DIAGEO NORTH AMERICA INC   ', 'BACARDI USA INC            ', 'JIM BEAM BRANDS COMPANY    ', 'ULTRA BEVERAGE COMPANY LLP ', 'MAJESTIC FINE WINES        ', 'PROXIMO SPIRITS INC.       ', 'STOLI GROUP,(USA) LLC      ',
 ...
 'CENTEUR IMPORTS LLC        ', 'AMERICAN SPIRITS EXCHANGE  ',             'UNCORKED       ', 'BRONCO WINE COMPANY        ', 'HIGHLAND WINE MERCHANTS LLC', 'MILTONS DISTRIBUTING CO    ', 'TRUETT HURST               ', 'SILVER MOUNTAIN CIDERS     ', 'FANTASY FINE WINES CORP    ', 'CAPSTONE INTERNATIONAL     ']
Length: 123, dtype: str

In [29]:
vendor_sales_summary['Description'].unique()

<StringArray>
[      'Tito's Handmade Vodka',     'Jack Daniels No 7 Black',            'Absolut 80 Proof',             'Ketel One Vodka',      'Capt Morgan Spiced Rum',            'Grey Goose Vodka',           'Smirnoff Traveler',                   'Tanqueray', 'Capt Morgan Original Barrel',       'Jameson Irish Whiskey',
 ...
 'Albero Sparkling Wh Organic',         'Firefly Ridge Chard',           'Debauchery Pnt Nr',       'Old St Nick's Egg Nog', 'Terruzzi & Puthod Vernaccia',  'Santa Rita Organic Svgn Bl',    'Aresti Pnt Nr Curico Vly',   'Smirnoff Light Strawberry',           'Crown Royal Apple', 'Concannon Glen Ellen Wh Zin']
Length: 8894, dtype: str

In [30]:
vendor_sales_summary['Volume'] = vendor_sales_summary['Volume'].astype('float64')
vendor_sales_summary.fillna(0, inplace=True)
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()

In [31]:
vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars'] - vendor_sales_summary['TotalPurchaseDollars']

vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesDollars'])*100

vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseQuantity']

vendor_sales_summary['SalestoPurchaseRatio'] = vendor_sales_summary['TotalSalesDollars']/vendor_sales_summary['TotalPurchaseDollars']

In [32]:
vendor_sales_summary

      VendorNumber                VendorName  Brand                   Description  PurchasePrice  ActualPrice  Volume  TotalPurchaseQuantity  TotalPurchaseDollars  TotalSalesQuantity  TotalSalesDollars  TotalSalesPrice  TotalExciseTax  FreightCost   GrossProfit  ProfitMargin  StockTurnover  SalestoPurchaseRatio
0             4425     MARTIGNETTI COMPANIES   3405         Tito's Handmade Vodka          23.19        28.99  1750.0               115609.0            2680972.71            160247.0       4.819073e+06        561512.37       294438.66    144929.24  2.138101e+06     44.367466       1.386112              1.797509
1             1128         BROWN-FORMAN CORP   1233       Jack Daniels No 7 Black          26.27        36.99  1750.0               101636.0            2669977.72            142049.0       5.101920e+06        672819.31       260999.20     68601.68  2.431942e+06     47.667192       1.397625              1.910847
2            17035         PERNOD RICARD USA   8068              Absolut 80 Proof          18.24        24.99  1750.0               136129.0            2482992.96            187140.0       4.538121e+06        461140.15       343854.07    123780.22  2.055128e+06     45.285875       1.374725              1.827682
3             3960  DIAGEO NORTH AMERICA INC   3545               Ketel One Vodka          21.89        29.99  1750.0                95215.0            2084256.35            135838.0       4.223108e+06        545778.28       249587.83    257032.07  2.138851e+06     50.646383       1.426645              2.026194
4             3960  DIAGEO NORTH AMERICA INC   4261        Capt Morgan Spiced Rum          16.17        22.99  1750.0               119516.0            1932573.72            200412.0       4.475973e+06        420050.01       368242.80    257032.07  2.543399e+06     56.823382       1.676863              2.316068
...            ...                       ...    ...                           ...            ...          ...     ...                    ...                   ...                 ...                ...              ...             ...          ...           ...           ...            ...                   ...
9891          3960  DIAGEO NORTH AMERICA INC   2626             Crown Royal Apple           1.42         1.99    50.0                    2.0                  2.84                14.0       2.786000e+01             5.97            0.73    257032.07  2.502000e+01     89.806174       7.000000              9.809859
9892          9815            WINE GROUP INC   8527   Concannon Glen Ellen Wh Zin           1.32         4.99   750.0                    2.0                  2.64                 5.0       1.595000e+01            10.96            0.55     27100.41  1.331000e+01     83.448276       2.500000              6.041667
9893          8004            SAZERAC CO INC   5683   Dr McGillicuddy's Apple Pie           0.39         0.49    50.0                    6.0                  2.34               134.0       6.566000e+01             1.47            7.04     50293.62  6.332000e+01     96.436186      22.333333             28.059829
9894          3960  DIAGEO NORTH AMERICA INC   3775  Smirnoff Sorbet Pine/Coconut           0.73         0.99    50.0                    1.0                  0.73               120.0       1.188000e+02            46.53            6.20    257032.07  1.180700e+02     99.385522     120.000000            162.739726
9895          7245      PROXIMO SPIRITS INC.   3065      Three Olives Grape Vodka           0.71         0.99    50.0                    1.0                  0.71                86.0       8.514000e+01            33.66            4.46     38994.78  8.443000e+01     99.166079      86.000000            119.915493

[9896 rows x 18 columns]

In [33]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS vendor_sales_summary (
            VendorNumber INT,
            VendorName VARCHAR(100),
            Brand INT,
            Description VARCHAR(255),
            PurchasePrice DECIMAL(10,2),
            ActualPrice DECIMAL(10,2),
            Volume INT,
            TotalPurchaseQuantity INT,
            TotalPurchaseDollars DECIMAL(15,2),
            TotalSalesQuantity INT,
            TotalSalesDollars DECIMAL(15,2),
            TotalSalesPrice DECIMAL(15,2),
            TotalExciseTax DECIMAL(15,2),
            FreightCost DECIMAL(15,2),
            GrossProfit DECIMAL(15,2),
            ProfitMargin DECIMAL(15,2),
            StockTurnover DECIMAL(15,2),
            SalesToPurchaseRatio DECIMAL(15,2),
            PRIMARY KEY (VendorNumber, Brand)
        )
    """))

In [34]:
tables = pd.read_sql("SHOW TABLES", engine)
print(tables)

  Tables_in_vendor_performance
0              begin_inventory
1                end_inventory
2              purchase_prices
3                    purchases
4                        sales
5               vendor_invoice
6         vendor_sales_summary

In [35]:
pd.read_sql("SELECT * FROM vendor_sales_summary", engine)

      VendorNumber                VendorName  Brand                   Description  PurchasePrice  ActualPrice  Volume  TotalPurchaseQuantity  TotalPurchaseDollars  TotalSalesQuantity  TotalSalesDollars  TotalSalesPrice  TotalExciseTax  FreightCost   GrossProfit  ProfitMargin  StockTurnover  SalestoPurchaseRatio
0             4425     MARTIGNETTI COMPANIES   3405         Tito's Handmade Vodka          23.19        28.99  1750.0               115609.0            2680972.71            160247.0       4.819073e+06        561512.37       294438.66    144929.24  2.138101e+06     44.367466       1.386112              1.797509
1             1128         BROWN-FORMAN CORP   1233       Jack Daniels No 7 Black          26.27        36.99  1750.0               101636.0            2669977.72            142049.0       5.101920e+06        672819.31       260999.20     68601.68  2.431942e+06     47.667192       1.397625              1.910847
2            17035         PERNOD RICARD USA   8068              Absolut 80 Proof          18.24        24.99  1750.0               136129.0            2482992.96            187140.0       4.538121e+06        461140.15       343854.07    123780.22  2.055128e+06     45.285875       1.374725              1.827682
3             3960  DIAGEO NORTH AMERICA INC   3545               Ketel One Vodka          21.89        29.99  1750.0                95215.0            2084256.35            135838.0       4.223108e+06        545778.28       249587.83    257032.07  2.138851e+06     50.646383       1.426645              2.026194
4             3960  DIAGEO NORTH AMERICA INC   4261        Capt Morgan Spiced Rum          16.17        22.99  1750.0               119516.0            1932573.72            200412.0       4.475973e+06        420050.01       368242.80    257032.07  2.543399e+06     56.823382       1.676863              2.316068
...            ...                       ...    ...                           ...            ...          ...     ...                    ...                   ...                 ...                ...              ...             ...          ...           ...           ...            ...                   ...
9891          3960  DIAGEO NORTH AMERICA INC   2626             Crown Royal Apple           1.42         1.99    50.0                    2.0                  2.84                14.0       2.786000e+01             5.97            0.73    257032.07  2.502000e+01     89.806174       7.000000              9.809859
9892          9815            WINE GROUP INC   8527   Concannon Glen Ellen Wh Zin           1.32         4.99   750.0                    2.0                  2.64                 5.0       1.595000e+01            10.96            0.55     27100.41  1.331000e+01     83.448276       2.500000              6.041667
9893          8004            SAZERAC CO INC   5683   Dr McGillicuddy's Apple Pie           0.39         0.49    50.0                    6.0                  2.34               134.0       6.566000e+01             1.47            7.04     50293.62  6.332000e+01     96.436186      22.333333             28.059829
9894          3960  DIAGEO NORTH AMERICA INC   3775  Smirnoff Sorbet Pine/Coconut           0.73         0.99    50.0                    1.0                  0.73               120.0       1.188000e+02            46.53            6.20    257032.07  1.180700e+02     99.385522     120.000000            162.739726
9895          7245      PROXIMO SPIRITS INC.   3065      Three Olives Grape Vodka           0.71         0.99    50.0                    1.0                  0.71                86.0       8.514000e+01            33.66            4.46     38994.78  8.443000e+01     99.166079      86.000000            119.915493

[9896 rows x 18 columns]

In [38]:
vendor_sales_summary.to_sql('vendor_sales_summary', con=engine, if_exists='replace', index=False)

9896

In [39]:
print(vendor_sales_summary.columns)

Index(['VendorNumber', 'VendorName', 'Brand', 'Description', 'PurchasePrice', 'ActualPrice', 'Volume', 'TotalPurchaseQuantity', 'TotalPurchaseDollars', 'TotalSalesQuantity', 'TotalSalesDollars', 'TotalSalesPrice', 'TotalExciseTax', 'FreightCost', 'GrossProfit', 'ProfitMargin', 'StockTurnover', 'SalestoPurchaseRatio'], dtype='str')

In [40]:
import numpy as np
np.isinf(vendor_sales_summary.select_dtypes(include='number')).sum()

VendorNumber             0
Brand                    0
PurchasePrice            0
ActualPrice              0
Volume                   0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalSalesQuantity       0
TotalSalesDollars        0
TotalSalesPrice          0
TotalExciseTax           0
FreightCost              0
GrossProfit              0
ProfitMargin             0
StockTurnover            0
SalestoPurchaseRatio     0
dtype: int64

In [41]:
vendor_sales_summary[
    vendor_sales_summary['TotalSalesDollars'] == 0
][
    ['TotalSalesDollars', 'GrossProfit', 'ProfitMargin']
]

      TotalSalesDollars  GrossProfit  ProfitMargin
2390                0.0    -17045.43           0.0
6290                0.0      -907.68           0.0
6442                0.0      -794.40           0.0
6633                0.0      -657.36           0.0
7053                0.0      -470.40           0.0
7246                0.0      -402.48           0.0
7284                0.0      -392.04           0.0
7539                0.0      -330.96           0.0
7587                0.0      -317.76           0.0
7627                0.0      -309.84           0.0
7675                0.0      -299.76           0.0
7722                0.0      -288.12           0.0
7784                0.0      -277.44           0.0
7801                0.0      -273.60           0.0
7962                0.0      -243.12           0.0
7999                0.0      -236.64           0.0
8077                0.0      -225.15           0.0
8108                0.0      -221.04           0.0
8172                0.0      -210.72           0.0
8230                0.0      -203.76           0.0
8433                0.0      -175.92           0.0
8568                0.0      -158.88           0.0
8606                0.0      -155.04           0.0
8699                0.0      -142.80           0.0
8724                0.0      -140.16           0.0
8726                0.0      -140.16           0.0
8730                0.0      -139.68           0.0
8745                0.0      -138.72           0.0
8751                0.0      -137.76           0.0
8883                0.0      -123.24           0.0
8898                0.0      -120.72           0.0
8936                0.0      -116.76           0.0
8951                0.0      -115.80           0.0
8986                0.0      -112.68           0.0
9018                0.0      -109.68           0.0
9019                0.0      -109.68           0.0
9031                0.0      -108.84           0.0
9047                0.0      -106.80           0.0
9048                0.0      -106.80           0.0
9049                0.0      -106.80           0.0
9085                0.0      -103.44           0.0
9115                0.0      -100.56           0.0
9146                0.0       -97.92           0.0
9157                0.0       -96.56           0.0
9173                0.0       -95.28           0.0
9195                0.0       -93.48           0.0
9326                0.0       -80.40           0.0
9341                0.0       -79.44           0.0
9393                0.0       -73.44           0.0
9434                0.0       -68.40           0.0
9463                0.0       -65.16           0.0
9654                0.0       -39.00           0.0
9843                0.0        -9.44           0.0
9874                0.0        -5.22           0.0

In [42]:
import numpy as np
vendor_sales_summary['ProfitMargin'] = vendor_sales_summary['ProfitMargin'].replace(
    [np.inf, -np.inf],
    0
)

In [43]:
np.isinf(vendor_sales_summary['ProfitMargin']).sum()

np.int64(0)

In [44]:
vendor_sales_summary[
    vendor_sales_summary['TotalSalesDollars'] == 0
][
    ['TotalSalesDollars', 'GrossProfit', 'ProfitMargin']
]

      TotalSalesDollars  GrossProfit  ProfitMargin
2390                0.0    -17045.43           0.0
6290                0.0      -907.68           0.0
6442                0.0      -794.40           0.0
6633                0.0      -657.36           0.0
7053                0.0      -470.40           0.0
7246                0.0      -402.48           0.0
7284                0.0      -392.04           0.0
7539                0.0      -330.96           0.0
7587                0.0      -317.76           0.0
7627                0.0      -309.84           0.0
7675                0.0      -299.76           0.0
7722                0.0      -288.12           0.0
7784                0.0      -277.44           0.0
7801                0.0      -273.60           0.0
7962                0.0      -243.12           0.0
7999                0.0      -236.64           0.0
8077                0.0      -225.15           0.0
8108                0.0      -221.04           0.0
8172                0.0      -210.72           0.0
8230                0.0      -203.76           0.0
8433                0.0      -175.92           0.0
8568                0.0      -158.88           0.0
8606                0.0      -155.04           0.0
8699                0.0      -142.80           0.0
8724                0.0      -140.16           0.0
8726                0.0      -140.16           0.0
8730                0.0      -139.68           0.0
8745                0.0      -138.72           0.0
8751                0.0      -137.76           0.0
8883                0.0      -123.24           0.0
8898                0.0      -120.72           0.0
8936                0.0      -116.76           0.0
8951                0.0      -115.80           0.0
8986                0.0      -112.68           0.0
9018                0.0      -109.68           0.0
9019                0.0      -109.68           0.0
9031                0.0      -108.84           0.0
9047                0.0      -106.80           0.0
9048                0.0      -106.80           0.0
9049                0.0      -106.80           0.0
9085                0.0      -103.44           0.0
9115                0.0      -100.56           0.0
9146                0.0       -97.92           0.0
9157                0.0       -96.56           0.0
9173                0.0       -95.28           0.0
9195                0.0       -93.48           0.0
9326                0.0       -80.40           0.0
9341                0.0       -79.44           0.0
9393                0.0       -73.44           0.0
9434                0.0       -68.40           0.0
9463                0.0       -65.16           0.0
9654                0.0       -39.00           0.0
9843                0.0        -9.44           0.0
9874                0.0        -5.22           0.0

In [45]:
vendor_sales_summary.to_sql(
    'vendor_sales_summary',
    con=engine,
    if_exists='replace',
    index=False
)

9896

In [46]:
pd.read_sql("SELECT * FROM vendor_sales_summary", engine)

      VendorNumber                VendorName  Brand                   Description  PurchasePrice  ActualPrice  Volume  TotalPurchaseQuantity  TotalPurchaseDollars  TotalSalesQuantity  TotalSalesDollars  TotalSalesPrice  TotalExciseTax  FreightCost   GrossProfit  ProfitMargin  StockTurnover  SalestoPurchaseRatio
0             4425     MARTIGNETTI COMPANIES   3405         Tito's Handmade Vodka          23.19        28.99  1750.0               115609.0            2680972.71            160247.0       4.819073e+06        561512.37       294438.66    144929.24  2.138101e+06     44.367466       1.386112              1.797509
1             1128         BROWN-FORMAN CORP   1233       Jack Daniels No 7 Black          26.27        36.99  1750.0               101636.0            2669977.72            142049.0       5.101920e+06        672819.31       260999.20     68601.68  2.431942e+06     47.667192       1.397625              1.910847
2            17035         PERNOD RICARD USA   8068              Absolut 80 Proof          18.24        24.99  1750.0               136129.0            2482992.96            187140.0       4.538121e+06        461140.15       343854.07    123780.22  2.055128e+06     45.285875       1.374725              1.827682
3             3960  DIAGEO NORTH AMERICA INC   3545               Ketel One Vodka          21.89        29.99  1750.0                95215.0            2084256.35            135838.0       4.223108e+06        545778.28       249587.83    257032.07  2.138851e+06     50.646383       1.426645              2.026194
4             3960  DIAGEO NORTH AMERICA INC   4261        Capt Morgan Spiced Rum          16.17        22.99  1750.0               119516.0            1932573.72            200412.0       4.475973e+06        420050.01       368242.80    257032.07  2.543399e+06     56.823382       1.676863              2.316068
...            ...                       ...    ...                           ...            ...          ...     ...                    ...                   ...                 ...                ...              ...             ...          ...           ...           ...            ...                   ...
9891          3960  DIAGEO NORTH AMERICA INC   2626             Crown Royal Apple           1.42         1.99    50.0                    2.0                  2.84                14.0       2.786000e+01             5.97            0.73    257032.07  2.502000e+01     89.806174       7.000000              9.809859
9892          9815            WINE GROUP INC   8527   Concannon Glen Ellen Wh Zin           1.32         4.99   750.0                    2.0                  2.64                 5.0       1.595000e+01            10.96            0.55     27100.41  1.331000e+01     83.448276       2.500000              6.041667
9893          8004            SAZERAC CO INC   5683   Dr McGillicuddy's Apple Pie           0.39         0.49    50.0                    6.0                  2.34               134.0       6.566000e+01             1.47            7.04     50293.62  6.332000e+01     96.436186      22.333333             28.059829
9894          3960  DIAGEO NORTH AMERICA INC   3775  Smirnoff Sorbet Pine/Coconut           0.73         0.99    50.0                    1.0                  0.73               120.0       1.188000e+02            46.53            6.20    257032.07  1.180700e+02     99.385522     120.000000            162.739726
9895          7245      PROXIMO SPIRITS INC.   3065      Three Olives Grape Vodka           0.71         0.99    50.0                    1.0                  0.71                86.0       8.514000e+01            33.66            4.46     38994.78  8.443000e+01     99.166079      86.000000            119.915493

[9896 rows x 18 columns]

In [47]:
vendor_sales_summary

      VendorNumber                VendorName  Brand                   Description  PurchasePrice  ActualPrice  Volume  TotalPurchaseQuantity  TotalPurchaseDollars  TotalSalesQuantity  TotalSalesDollars  TotalSalesPrice  TotalExciseTax  FreightCost   GrossProfit  ProfitMargin  StockTurnover  SalestoPurchaseRatio
0             4425     MARTIGNETTI COMPANIES   3405         Tito's Handmade Vodka          23.19        28.99  1750.0               115609.0            2680972.71            160247.0       4.819073e+06        561512.37       294438.66    144929.24  2.138101e+06     44.367466       1.386112              1.797509
1             1128         BROWN-FORMAN CORP   1233       Jack Daniels No 7 Black          26.27        36.99  1750.0               101636.0            2669977.72            142049.0       5.101920e+06        672819.31       260999.20     68601.68  2.431942e+06     47.667192       1.397625              1.910847
2            17035         PERNOD RICARD USA   8068              Absolut 80 Proof          18.24        24.99  1750.0               136129.0            2482992.96            187140.0       4.538121e+06        461140.15       343854.07    123780.22  2.055128e+06     45.285875       1.374725              1.827682
3             3960  DIAGEO NORTH AMERICA INC   3545               Ketel One Vodka          21.89        29.99  1750.0                95215.0            2084256.35            135838.0       4.223108e+06        545778.28       249587.83    257032.07  2.138851e+06     50.646383       1.426645              2.026194
4             3960  DIAGEO NORTH AMERICA INC   4261        Capt Morgan Spiced Rum          16.17        22.99  1750.0               119516.0            1932573.72            200412.0       4.475973e+06        420050.01       368242.80    257032.07  2.543399e+06     56.823382       1.676863              2.316068
...            ...                       ...    ...                           ...            ...          ...     ...                    ...                   ...                 ...                ...              ...             ...          ...           ...           ...            ...                   ...
9891          3960  DIAGEO NORTH AMERICA INC   2626             Crown Royal Apple           1.42         1.99    50.0                    2.0                  2.84                14.0       2.786000e+01             5.97            0.73    257032.07  2.502000e+01     89.806174       7.000000              9.809859
9892          9815            WINE GROUP INC   8527   Concannon Glen Ellen Wh Zin           1.32         4.99   750.0                    2.0                  2.64                 5.0       1.595000e+01            10.96            0.55     27100.41  1.331000e+01     83.448276       2.500000              6.041667
9893          8004            SAZERAC CO INC   5683   Dr McGillicuddy's Apple Pie           0.39         0.49    50.0                    6.0                  2.34               134.0       6.566000e+01             1.47            7.04     50293.62  6.332000e+01     96.436186      22.333333             28.059829
9894          3960  DIAGEO NORTH AMERICA INC   3775  Smirnoff Sorbet Pine/Coconut           0.73         0.99    50.0                    1.0                  0.73               120.0       1.188000e+02            46.53            6.20    257032.07  1.180700e+02     99.385522     120.000000            162.739726
9895          7245      PROXIMO SPIRITS INC.   3065      Three Olives Grape Vodka           0.71         0.99    50.0                    1.0                  0.71                86.0       8.514000e+01            33.66            4.46     38994.78  8.443000e+01     99.166079      86.000000            119.915493

[9896 rows x 18 columns]

In [48]:
vendor_sales_summary.to_excel("vendor_sales_summary.xlsx", index=False)